2024-12-14 06:34:24,805 - __main__ - INFO - Initialized Hugging Face Inference Client with model: meta-llama/Llama-3.2-1B
2024-12-14 06:36:01,079 - __main__ - INFO - Initialized Hugging Face Inference Client with model: meta-llama/Llama-3.2-1B
2024-12-14 06:39:12,114 - __main__ - INFO - Initialized Hugging Face Inference Client with model: meta-llama/Llama-3.2-1B
2024-12-14 06:39:13,266 - __main__ - INFO - User input: hello

2024-12-14 06:39:13,274 - __main__ - INFO - parsed_input. = {}
2024-12-14 06:39:13,484 - __main__ - INFO - Input successfully parsed and converted to dataframe.
2024-12-14 06:39:16,640 - __main__ - ERROR - Error during response generation: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2024-12-14 06:39:17,993 - __main__ - ERROR - Traceback (most recent call last):
  File "/home/mazen/Desktop/new/new.py", line 278, in generate_response
    prompt = self.check_input_prompt(df)
  File "/home/mazen/Desktop/new/new.py", line 272, in check_input_prompt
    if DataChecking.is_context_complete():
  File "/home/mazen/Desktop/new/new.py", line 183, in is_context_complete
    if context.isna().count()>0:
  File "/home/mazen/Desktop/new/etisalatEnv/lib/python3.8/site-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

